//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kütüp_otamasyon2.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class kitaplarim
    {
        public int kitapid { get; set; }
        public string kitapisim { get; set; }
        public string kitapyazar { get; set; }
        public string kitapdili { get; set; }
        public string kitapyayinevi { get; set; }
        public string kitaptür { get; set; }
        public string kitapadet { get; set; }
        public string kitapsayfasayisi { get; set; }
        public string kitapbasimyili { get; set; }
    }
}
