//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kütüp_otamasyon2.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uyeler
    {
        public int uye_id { get; set; }
        public string uye_isim { get; set; }
        public string uye_soyisim { get; set; }
        public Nullable<System.DateTime> uye_olusturmatarihi { get; set; }
        public string uye_kullaniciadi { get; set; }
        public string uye_sifre { get; set; }
        public string uye_yetki { get; set; }
        

    }
}
